/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package BAB3;

/**
 *
 * @author joy
 */
public class GUISnackStore extends javax.swing.JFrame {

    /**
     * Creates new form GUISnackStore
     */
    public GUISnackStore() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbPromo = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        spinJumlah = new javax.swing.JSpinner();
        btnBeli = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaOutput = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cmbSnack = new javax.swing.JComboBox<>();
        rbUmum = new javax.swing.JRadioButton();
        rbMember = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cbPromo.setText("Promo Diskon 20 %");

        jLabel4.setText("Jumlah :");

        btnBeli.setText("Beli Skarang");
        btnBeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBeliActionPerformed(evt);
            }
        });

        btnReset.setText("Reset Form");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        jLabel1.setText("Snack Store");

        areaOutput.setColumns(20);
        areaOutput.setRows(5);
        jScrollPane1.setViewportView(areaOutput);

        jLabel2.setText("Pilihan Snack :");

        jLabel3.setText("Tipe Pembeli :");

        jLabel5.setText("Status Bar");

        cmbSnack.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choco Crunch", "Cheese Stick" }));
        cmbSnack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSnackActionPerformed(evt);
            }
        });

        rbUmum.setText("Umum");
        rbUmum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbUmumActionPerformed(evt);
            }
        });

        rbMember.setText("Member");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(167, 167, 167)
                .addComponent(jLabel1)
                .addGap(14, 14, 14))
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(17, 17, 17)
                                        .addComponent(rbUmum)
                                        .addGap(49, 49, 49)
                                        .addComponent(rbMember)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(cmbSnack, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(spinJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(58, 58, 58))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(cbPromo)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnBeli)
                                .addGap(18, 18, 18)
                                .addComponent(btnReset)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbSnack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(rbUmum)
                    .addComponent(rbMember))
                .addGap(18, 18, 18)
                .addComponent(cbPromo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(spinJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBeli)
                    .addComponent(btnReset))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBeliActionPerformed
        // TODO add your handling code here:
        // Ambil snack yang dipilih dari ComboBox
        String snackDipilih = cmbSnack.getSelectedItem().toString();
        // Cek apakah promo dan membership aktif
        boolean isPromo = cbPromo.isSelected();
        boolean isMember = rbMember.isSelected();
        // Ambil jumlah item yang ingin dibeli dari Spinner
        int jumlah = (Integer) spinJumlah.getValue();
        // Objek snack (masih kosong, akan diisi nanti)
        SnackStore snack = null;
        // Buat objek sesuai snack yang dipilih
        if (snackDipilih.equals("Cheese Stick")) {
            snack = new SnackLocal("Cheese Stick", 6000, 20, "Pedas Balado ");
        } else if (snackDipilih.equals("Choco Crunch")) {
            snack = new SnackImport("Choco Crunch", 8000, 15, "Jepang");
        }
        // Jika snack tidak ditemukan
        if (snack == null) {
            areaOutput.setText("Snack tidak ditemukan.");
            jLabel5.setText("Status: Gagal memilih snack");
            return;
        }
        // Jika stok tidak mencukupi
        if (jumlah > snack.stok) {
            areaOutput.setText("Stok tidak cukup.\nSisa stok: " + snack.stok + " pcs");
            jLabel5.setText("Status: Gagal - stok tidak cukup");
            return;
        }
        // Hitung total harga (pakai promo kalau dicentang)
        double total = snack.hitungTotalHarga(jumlah, isPromo);
        // Jika pembeli adalah member, potong 10% lagi
        if (isMember) total *= 0.9;
        // Kurangi stok setelah pembelian
        snack.kurangiStok(jumlah);
        // Buat string output hasil pembelian
        String output = "Pembelian Berhasil!\n";
        output += snack.tampilkanDetailUmum() + "\n";
        // Tambahkan info khusus berdasarkan tipe snack
        if (snack instanceof SnackLocal) {
            output += ((SnackLocal) snack).tampilkanKhusus() + "\n";
        } else if (snack instanceof SnackImport) {
            output += ((SnackImport) snack).tampilkanKhusus() + "\n";
        }
        // Tambahkan info jenis pembeli, jumlah beli, total harga, dan sisa stok
        output += "Jenis Pembeli: " + (isMember ? "Member" : "Umum") + "\n";
        output += "Jumlah Beli : " + jumlah + " pcs\n";
        output += "Total Harga : Rp" + total + "\n";
        output += "Sisa Stok   : " + snack.stok + " pcs";
        // Tampilkan output ke areaOutput dan update status
        areaOutput.setText(output);
        jLabel5.setText("Status: Pembelian berhasil");
    }//GEN-LAST:event_btnBeliActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        // Kembalikan pilihan snack ke item pertama (index 0)
        cmbSnack.setSelectedIndex(0);
        // Set radio button "Umum" sebagai default
        rbUmum.setSelected(true);
        // Hapus centang promo (set tidak aktif)
        cbPromo.setSelected(false);
        // Kembalikan jumlah pembelian ke 1
        spinJumlah.setValue(1);
        // Kosongkan area output
        areaOutput.setText("");
        // Ubah status bar jadi info bahwa form telah direset
        jLabel5.setText("Status: Form telah direset");
    }//GEN-LAST:event_btnResetActionPerformed

    private void cmbSnackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSnackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbSnackActionPerformed

    private void rbUmumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbUmumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbUmumActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUISnackStore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUISnackStore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUISnackStore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUISnackStore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUISnackStore().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaOutput;
    private javax.swing.JButton btnBeli;
    private javax.swing.JButton btnReset;
    private javax.swing.JCheckBox cbPromo;
    private javax.swing.JComboBox<String> cmbSnack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rbMember;
    private javax.swing.JRadioButton rbUmum;
    private javax.swing.JSpinner spinJumlah;
    // End of variables declaration//GEN-END:variables
}
