/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package BAB7;
import BAB7.GUISnackImport;
import BAB7.GUISnackLocal;

/**
 *
 * @author ASUS
 */
public class GUISnackStore extends javax.swing.JFrame {

    /**
     * Creates new form GUISnackStore
     */
    public GUISnackStore() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        GUISnackLocal = new javax.swing.JMenuItem();
        GUISnackImport = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Home");
        mainPanel.add(jMenu1);

        jMenu2.setText("Form");

        GUISnackLocal.setText("SnackLocal");
        GUISnackLocal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GUISnackLocalActionPerformed(evt);
            }
        });
        jMenu2.add(GUISnackLocal);

        GUISnackImport.setText("SnackImport");
        GUISnackImport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GUISnackImportActionPerformed(evt);
            }
        });
        jMenu2.add(GUISnackImport);

        mainPanel.add(jMenu2);

        setJMenuBar(mainPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GUISnackLocalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GUISnackLocalActionPerformed
        // TODO add your handling code here:
        GUISnackLocal SnackLocal = new GUISnackLocal();
        SnackLocal.setVisible(true);
    }//GEN-LAST:event_GUISnackLocalActionPerformed

    private void GUISnackImportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GUISnackImportActionPerformed
        // TODO add your handling code here:
        GUISnackImport SnackImport = new GUISnackImport();
        SnackImport.setVisible(true);
    }//GEN-LAST:event_GUISnackImportActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUISnackStore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUISnackStore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUISnackStore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUISnackStore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUISnackStore().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem GUISnackImport;
    private javax.swing.JMenuItem GUISnackLocal;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar mainPanel;
    // End of variables declaration//GEN-END:variables
}
